# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
    - gripper_palm_finger_1_joint
    - gripper_finger_1_joint_1
    - gripper_finger_1_joint_2
    - gripper_finger_1_joint_3
    - gripper_palm_finger_2_joint
    - gripper_finger_2_joint_1
    - gripper_finger_2_joint_2
    - gripper_finger_2_joint_3
    - gripper_finger_middle_joint_1
    - gripper_finger_middle_joint_2
    - gripper_finger_middle_joint_3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_finger_1_joint_1
      - gripper_finger_1_joint_2
      - gripper_finger_1_joint_3
      - gripper_finger_2_joint_1
      - gripper_finger_2_joint_2
      - gripper_finger_2_joint_3
      - gripper_finger_middle_joint_1
      - gripper_finger_middle_joint_2
      - gripper_finger_middle_joint_3
manipulator_controller:
  type: position_controllers/JointPositionController
  joints:
    - robot_shoulder_pan_joint
    - robot_shoulder_lift_joint
    - robot_elbow_joint
    - robot_wrist_1_joint
    - robot_wrist_2_joint
    - robot_wrist_3_joint
  gains:
    robot_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1