manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - robot_shoulder_pan_joint
     - robot_shoulder_lift_joint
     - robot_elbow_joint
     - robot_wrist_1_joint
     - robot_wrist_2_joint
     - robot_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      robot_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      robot_elbow_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_3_joint: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# Gripper controller
gripper_controller:
  type: effort_controllers/GripperActionController
  joint: gripper_robotiq_85_left_knuckle_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

  gains:
    gripper_robotiq_85_left_knuckle_joint: {p: 100.0, i: 1.0, d: 0.01, i_clamp: 1}

  # Joint state controller (publish joint states)
  joint_state_controller:
    publish_rate: 125
    type: joint_state_controller/JointStateController

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - robot_shoulder_pan_joint
     - robot_shoulder_lift_joint
     - robot_elbow_joint
     - robot_wrist_1_joint
     - robot_wrist_2_joint
     - robot_wrist_3_joint