manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - robot_shoulder_pan_joint
     - robot_shoulder_lift_joint
     - robot_elbow_joint
     - robot_wrist_1_joint
     - robot_wrist_2_joint
     - robot_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      robot_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      robot_elbow_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      robot_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    robot_shoulder_pan_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    robot_shoulder_lift_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    robot_elbow_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    robot_wrist_1_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    robot_wrist_2_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
    robot_wrist_3_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: gripper_robotiq_85_left_knuckle_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

  stop_trajectory_duration: 0.5
  state_publish_rate: 25

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - robot_shoulder_pan_joint
     - robot_shoulder_lift_joint
     - robot_elbow_joint
     - robot_wrist_1_joint
     - robot_wrist_2_joint
     - robot_wrist_3_joint