controller_list:
  - name: fake_manipulator_controller
    joints:
      - robot_shoulder_pan_joint
      - robot_shoulder_lift_joint
      - robot_elbow_joint
      - robot_wrist_1_joint
      - robot_wrist_2_joint
      - robot_wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_finger_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home
  - group: gripper
    pose: opened