ur10e3:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  m_controller:
    type: position_controllers/JointPositionController
    joints:
      - elbow_joint
      - shoulder_lift_joint
      - shoulder_pan_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    gains:
      elbow_joint: { p: 100, d: 1, i: 1, i_clamp: 1}
      shoulder_lift_joint: { p: 100, d: 1, i: 1, i_clamp: 1}
      shoulder_pan_joint: { p: 100, d: 1, i: 1, i_clamp: 1}
      wrist_1_joint: { p: 100, d: 1, i: 1, i_clamp: 1}
      wrist_2_joint: { p: 100, d: 1, i: 1, i_clamp: 1}
      wrist_3_joint: { p: 100, d: 1, i: 1, i_clamp: 1}

  controller_list:
    - name: ur10e3/m_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - elbow_joint
        - shoulder_lift_joint
        - shoulder_pan_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint